name: hisma_extra
description: Extra classes on top of the Hisma hierarchical state machine implementation to simplify its usage.
homepage: https://github.com/tamas-p/hisma
repository: https://github.com/tamas-p/hisma
version: 0.1.1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  hisma: ^0.1.1
dev_dependencies:  
  hisma_console_monitor: ^0.1.1
  hisma_visual_monitor: ^0.1.1
  lint: ^1.10.0
  test: ^1.16.0
