name: hisma_visual_monitor
description: Visual monitor for Hisma, a hierarchical state machine implementation.
homepage: https://github.com/tamas-p/hisma
repository: https://github.com/tamas-p/hisma
version: 0.1.0

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  hisma: ^0.1.0
  logging: ^1.1.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  lint: ^1.7.2
  test: ^1.16.0
