name: hisma_console_monitor
description: Simple state machine monitor implementation that writes to the console for the Hisma package.
homepage: https://github.com/tamas-p/hisma
repository: https://github.com/tamas-p/hisma
version: 0.1.1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  hisma: ^0.1.1
dev_dependencies:
  lint: ^1.10.0
  test: ^1.16.0
